### ISSUE TITLE
Shortcodes not recognized in Ajax calls

### ISSUE THREAD

**Issue by pavelevap** [pippinsplugins/Restrict-Content-Pro#119]
Hi,

we are using Ajax calls for loading posts and shortcodes are not recognized.
It is probably caused by `is_admin()` check in `restrict-content-pro.php` (which is always true for Ajax calls) for loading `includes/shortcodes.php` file.

Line 164 should be probably changed from:

`if( is_admin() ) {`

to:

`if( is_admin() && ( !defined( 'DOING_AJAX' ) || !DOING_AJAX ) ) {`

**Comment by pippinsplugins** [comment]
Yep you're right. I've gone ahead and fixed it by making it a globally included file: https://github.com/pippinsplugins/Restrict-Content-Pro/commit/86d9278657545d7d7faa1f68215c163ae3f919d4

**Comment by pavelevap** [comment]
Great, thank you!
