### ISSUE TITLE
Add support for User Switching plugin

### ISSUE THREAD

**Issue by pippinsplugins** [pippinsplugins/Restrict-Content-Pro#129]
If User Switching is activated, a Switch To link should be shown on the Members page and the Edit member screen.

**Comment by tnorthcutt** [comment]
I can probably tackle this if you'd like.

My initial thought is to have e.g. `rcp_is_user_switching_active()` and `rcp_get_user_switching_url()` functions – does it make sense to do it that way? If so, any preference on where they should go?

**Comment by pippinsplugins** [comment]
I"d love the help! I like the idea of a conditional and then the helper
function for the URL.

**Comment by tnorthcutt** [comment]
Based on johnbillion's comments in https://github.com/johnbillion/user-switching/issues/5 I'm planning on not using a separate function to check if the user switching plugin is active. Instead, I'll add a method to `RCP_Member` (something like `switch_to_url()`), and a corresponding wrapper function in `includes/member-functions.php`.

**Comment by pippinsplugins** [comment]
Sounds great!

**Comment by cliffordp** [comment]
https://premium.wpmudev.org/project/protected-content/ has a REALLY nice feature in the Admin Bar to simulate as a user: /wp-admin/?action=ms_simulate&membership_id=167&_wpnonce=64c30c329b

![screen shot 2015-05-16 at 8 33 57 am](https://cloud.githubusercontent.com/assets/1812179/7666299/60e0f360-fba6-11e4-91a1-e792c52b452c.png)

![screen shot 2015-05-16 at 8 34 51 am](https://cloud.githubusercontent.com/assets/1812179/7666303/90c8b45a-fba6-11e4-8a4c-8b649ee39576.png)

![screen shot 2015-05-16 at 8 35 00 am](https://cloud.githubusercontent.com/assets/1812179/7666305/945d7d58-fba6-11e4-83b5-e228c615defe.png)

**Comment by pippinsplugins** [comment]
Thanks for the suggestion! I'll have to look into that.

**Comment by cliffordp** [comment]
Another alternative could be something like this: https://gist.github.com/strangerstudios/7357594
