### ISSUE TITLE
Page dropdowns can be ambiguous

### ISSUE THREAD

**Issue by tnorthcutt** [pippinsplugins/Restrict-Content-Pro#130]
The signup form tab of the settings page (`/wp-admin/admin.php?page=rcp-settings&settings-updated=true#forms`) contains two select lists of pages. Currently, these only display the page title, and can thus be ambiguous:
![image](https://cloud.githubusercontent.com/assets/796639/6112070/4379694a-b053-11e4-8a54-c688551e57bf.png)

Since the list of pages is fetched by `get_pages()`, one possible solution would be to display the page name and guid, for instance `Thank You - http://example.com/thank-you/`.

Of course, that could result in some pretty long URLs being displayed, which could be messy. A possible solution to that issue could be only displaying GUIDs if page names alone are ambiguous (detecting if duplicate page names exist, basically).

I'd love to hear other ideas & feedback on this. If there's a clearly desired solution, I'm happy to put together a PR with it.

**Comment by pippinsplugins** [comment]
Hmm. Maybe if we just display it with the proper hierarchy so you see the indention. Would that suffice?

**Comment by tnorthcutt** [comment]
Not sure what you mean by indention. Just to clarify, those two `Thank You` pages aren't in a hierarchical relationship; sorry if that was unclear. They just happen to have the same title (silly, I know).

Does that make sense?

**Comment by cliffordp** [comment]
`%post_title% (ID: %post_id%)`

e.g.
 - Thank You (ID: 24)
 - Thank You (ID: 92)

**Comment by tnorthcutt** [comment]
I considered that option, but my concern is that regular users wouldn't understand the implications of a post ID, or know where to find it, whereas they would hopefully be more likely to understand the implications of a URL. Does that make sense?

**Comment by cliffordp** [comment]
URL could get really long. Slug might be same unless you include everything after site_url().

**Comment by tnorthcutt** [comment]
@cliffordp are you saying slug could be the same because of cases where e.g. you might have a 2nd level (or lower) page with the same slug as a first level page?

Something like:
`http://example.com/first-level/thank-you`
`http://example.com/thank-you`
`http://example.com/another-first-level/second-level/third-level/thank-you`

If so, then combining slug with Pippin's suggestion for showing hierarchy would go a long way toward removing ambiguity.

@pippinsplugins could you weigh in when you have a chance?

**Comment by pippinsplugins** [comment]
I'm inclined to agree with @cliffordp's proposal and add the IDs. It's not as clear for users that don't know what page IDs are, but it's better than having a drop down that is 10,000ft long because of super long page names.
