### ISSUE TITLE
Stripe credit card expiration display is not customizable

### ISSUE THREAD

**Issue by tnorthcutt** [pippinsplugins/Restrict-Content-Pro#131]
*This applies to the Stripe addon, but @pippinsplugins suggested I log an issue here since it's being added to core.*

Currently, the expiration date portion of the registration form looks like this when using the Stripe addon:
 
![2015-02-10 at 1 56 pm](https://cloud.githubusercontent.com/assets/796639/6135272/dca70512-b12c-11e4-8388-b4bc560cf244.png)

Obviously it's subjective, but to me the `/` by itself is ugly and unnecessary. Unfortunately, there's no way to target that element that I can tell, since it's a `span` with no id or class applied to it. Adding a simple class such as `expiry-separator` would be very welcome.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by tnorthcutt** [comment]
@pippinsplugins do you plan to add the `expiry-separator` class? I have a client site I need to do this on, so if you already know how you'll do this in core, I can just mimic that in what I do so it'll work seamlessly on update :smile:

**Comment by pippinsplugins** [comment]
Yes, I'll add it as `rcp-expiry-separator`.

Note, the card form is also going to exist as a template file in 2.1.
