### ISSUE TITLE
Add support for cancelling PayPal subscriptions

### ISSUE THREAD

**Issue by pippinsplugins** [pippinsplugins/Restrict-Content-Pro#133]
Turns out the API allows us to cancel subscriptions in PayPal: https://gist.github.com/thomasgriffin/188e9ae21576a9b567cb

**Comment by carter2422** [comment]
Fantastic!

**Comment by pippinsplugins** [comment]
@carter2422 Would you be up for doing some testing on this?

**Comment by carter2422** [comment]
Absolutely! Is it ready for testing now @pippinsplugins?

**Comment by pippinsplugins** [comment]
Super close. I'll let you know how to test shortly.

**Comment by pippinsplugins** [comment]
Ok to test:

1. Put `issue/133` branch on a live site (so that the IPN can work)
2. Signup for a recurring subscription through PayPal
3. Confirm the member is set to `active` properly and that they have a `Profile ID` in their `Restrict > Members > Edit` screen.
4. Log in as that user (if you are not already) and visit the page that has the `[subscription_details]` short code on it.
5. Click `Cancel Subscription`
6. It should take a moment and then you should be redirected to the same page but now it will show `Renew Your Subscription` (or might be blank).

**Comment by pippinsplugins** [comment]
Oh, also, you must enter your API credentials in `Restrict > Settings` for PayPal.

**Comment by pippinsplugins** [comment]
I've tested this on a live site now and it worked beautifully.

**Comment by pippinsplugins** [comment]
- [ ] Add a notice to page after successful cancellation

**Comment by pippinsplugins** [comment]
![screen shot 2015-04-03 at 11 36 04 am](https://cloud.githubusercontent.com/assets/1034109/6985133/a07f320c-d9f5-11e4-8b22-21659de5ed24.png)
