### ISSUE TITLE
Log in user and create account at the same time

### ISSUE THREAD

**Issue by JakePT** [pippinsplugins/Restrict-Content-Pro#134]
One issue I've run into is that the plugin appears to log the user in after payment is received, but registers the account as soon as the registration form is validated.

For example, when paying by credit card with the PayPal extension, if the credit card no. is incorrect the account still gets created, but the user doesn't get signed in or subscribed. This led to a situation where someone's payment would fail, and they'd be kicked back to the registration form where they'd try to enter the correct information only to be told the email address was taken.

The user should be logged in as soon as the account is created, and also, if possible, the account probably shouldn't be created until they've paid properly.

**Comment by pippinsplugins** [comment]
This is a bug I'm working on resolving with v2.1. It's getting taken care of largely by getting the payment gateways integrated into the core plugin instead of as add-ons along with the introduction of the new gateways API #109

**Comment by misulicus** [comment]
not sure on how its supposed to work but i did noticed this.
Right after registration the user is created even if let`s say my payment failed or i abandoned. Next time i`l try it will say my email is taken.

Once i do manage to register and subscribe i`m redirected to the store but not logged in. And if the website owner does not show a Login menu anywhere me (As a noobie) i got no clue about going to wp-login page to login.

Idea: on the pages where content is restricted and when user tries to view it as NOT logged in redirect them to a login page or someplace else.

https://dl.dropboxusercontent.com/u/16683640/WPeCommerce-Dev/2015-05-22_0035.png

That does not seem to work, and its not redireting me to that page when i try to view a restricted page.

**Comment by misulicus** [comment]
Ok after looking at the code it seems that setting above ONLY works when Hide Premium Posts is enabled BUT i had no idea they depend on each other.
Maybe group settings if one requires the other
