### ISSUE TITLE
Bundle PayPal Pro / Express into core

### ISSUE THREAD

**Issue by pippinsplugins** [pippinsplugins/Restrict-Content-Pro#140]
They need to be added to core, just like Stripe.

Related #133

**Comment by pippinsplugins** [comment]
This will be 2.2 in order to give a bit more time for Stripe to be tested on the new gateway API.

**Comment by pippinsplugins** [comment]
I've changed my mind and this will now be 2.1.

**Comment by carter2422** [comment]
:+1:

**Comment by pippinsplugins** [comment]
This is ready for testing.

Anyone want to help test?
