### ISSUE TITLE
Should RCP_Member->cancel() call set_expiration_date()

### ISSUE THREAD

**Issue by tnorthcutt** [pippinsplugins/Restrict-Content-Pro#146]
The [inline comment](https://github.com/pippinsplugins/Restrict-Content-Pro/blob/f401521fa6413f1624fef657efbffcf195bc3c02/includes/class-rcp-member.php#L188) for `RCP_Member->cancel()` says:
```
Sets a member's membership as cancelled by updating status and expiration date
```
But, that method doesn't actually update the expiration date... perhaps it should?

**Comment by pippinsplugins** [comment]
Oops, good catch.

No, that method shouldn't update expiration, at least I don't think so. A member can still access content when their subscription is cancelled if the expiration date is still in the future.
