### ISSUE TITLE
Payment gateway settings reset

### ISSUE THREAD

**Issue by misulicus** [pippinsplugins/Restrict-Content-Pro#160]
Once you deactivate the plugin and reactivate the Payment settings all get reset and you have to do them again.

Also on that page it shows all the paypal/stripe api boxes. I think it should maybe hide the payment api fields and show them when the gateway that uses them is selected.

**Comment by pippinsplugins** [comment]
Fixed!

Improving the settings display is something I've wanted to do for a while.
