### ISSUE TITLE
Add labels to subscription levels

### ISSUE THREAD

**Issue by sumobi** [pippinsplugins/Restrict-Content-Pro#168]
I think the subscription levels should have labels so you can easily click on the text and change the level

![screen shot 2015-05-24 at 9 04 30 pm](https://cloud.githubusercontent.com/assets/52581/7787290/8eb06740-0258-11e5-902d-9b05838bc926.png)

**Comment by pippinsplugins** [comment]
@sumobi This changes the display of the levels:

Before: https://cloudup.com/c8RciQ0mKZu

After: https://cloudup.com/cyFzspcTQ0f

Was that intentional?

**Comment by pippinsplugins** [comment]
@sumobi

**Comment by sumobi** [comment]
@pippinsplugins no, radio buttons should still be on left, let me have a look and see why that is

**Comment by pippinsplugins** [comment]
@sumobi did you get a chance to look at this?

**Comment by sumobi** [comment]
@pippinsplugins see https://github.com/pippinsplugins/Restrict-Content-Pro/pull/169

Fixed the issue with labels above, fixed label id's so you can click on them and added a cursor rule so you get that sweet hand icon on the labels

2015 with its 100% wide inputs:

![screen shot 2015-08-25 at 7 54 26 pm](https://cloud.githubusercontent.com/assets/52581/9461518/613ff092-4b63-11e5-8aa4-0086e13d9566.png)

2013:

![screen shot 2015-08-25 at 7 53 55 pm](https://cloud.githubusercontent.com/assets/52581/9461519/614d152e-4b63-11e5-94b2-769c6ddf7ec1.png)

**Comment by pippinsplugins** [comment]
Thanks! I'll test again and see how it works
