### ISSUE TITLE
Fatal error when registering

### ISSUE THREAD

**Issue by sumobi** [pippinsplugins/Restrict-Content-Pro#170]
When registering with`Credit/Debi`t card I get:

    PHP Fatal error:  Call to private method RCP_Payment_Gateway::add_error() from context 'RCP_Payment_Gateway_PayPal_Pro' in /wp-content/plugins/Restrict-Content-Pro/includes/gateways/class-rcp-payment-gateway-paypal-pro.php on line 164

I suspect this is because I simply haven't entered any credentials for PayPal Pro in the settings, only enabled the gateway. I also haven't enabled sandbox mode.

![screen shot 2015-05-24 at 9 19 39 pm](https://cloud.githubusercontent.com/assets/52581/7787342/b8068352-025a-11e5-989a-4c31c60cd73d.png)

Using Stripe I don't get a fatal error but I get the following outputted in the console:

    Uncaught Error: You did not set a valid publishable key. Call Stripe.setPublishableKey() with your publishable key. For more info, see https://stripe.com/docs/stripe.js

I think the registration form should gracefully fallback in both instances rather than showing a fatal error or freezing and showing an error in the console.

**Comment by pippinsplugins** [comment]
Agreed.

**Comment by ghost1227** [comment]
Fallback to what?

**Comment by pippinsplugins** [comment]
Fixed the fatal error. Can address the JS error later. Not as crucial.
