### ISSUE TITLE
Change description divs to paragraph tags

### ISSUE THREAD

**Issue by sumobi** [pippinsplugins/Restrict-Content-Pro#172]
For consistency with WordPress core (and because it looks a lot nicer IMO) we should change the description divs in the settings to paragraph tags:

Before:

![screen shot 2015-05-24 at 9 39 52 pm](https://cloud.githubusercontent.com/assets/52581/7787386/7f224316-025d-11e5-9901-db5a0d48134e.png)

After:

![screen shot 2015-05-24 at 9 39 37 pm](https://cloud.githubusercontent.com/assets/52581/7787387/84e2d68a-025d-11e5-9ee1-557806c7fc43.png)

**Comment by pippinsplugins** [comment]
#173
