### ISSUE TITLE
Missing CC field

### ISSUE THREAD

**Issue by ghost1227** [pippinsplugins/Restrict-Content-Pro#175]
In one specific set of circumstances, the CC field fails to show. Reproducible as follows:

1. Install and activate RCP
1. Activate Strip or PayPal Pro (tested in Sandbox Mode)
1. Add two products
  1. First (auto-selected) product MUST be free
  2. Second product should be paid
1. Go to `/register` and switch the selected option to the paid option

For some reason, if the auto-selected option is free and you switch to a paid option, the credit card form never shows?

**Comment by pippinsplugins** [comment]
Aha! I've just replicated it.

**Comment by ghost1227** [comment]
Seriously? That fast? You suck.

**Comment by pippinsplugins** [comment]
It helps when you wrote the code ;)
