### ISSUE TITLE
problem with installation

### ISSUE THREAD

**Issue by colomet** [pippinsplugins/Restrict-Content-Pro#185]
The plugin generated 2327 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.

**Comment by pippinsplugins** [comment]
This is a known bug that I'm working on fixing (another issue opened on it
already).

It won't cause any negative affects.

**Comment by colomet** [comment]
ok. thanks
