### ISSUE TITLE
Login template needs actions

### ISSUE THREAD

**Issue by mihche** [pippinsplugins/Restrict-Content-Pro#191]
Add actions and filters in login template as they are in register. 
Ex: do_action( 'rcp_before_register_form_fields' );
The login template should have something similar like 
do_action( 'rcp_before_login_form_fields' );

**Comment by pippinsplugins** [comment]
Inside or outside of the `form` element?

There are ones outside of it:

```php
	do_action( 'rcp_before_login_form' );

	rcp_get_template_part( 'login' );

	do_action( 'rcp_after_login_form' );
```

**Comment by mihche** [comment]
Perfect!
Thanks
