### ISSUE TITLE
Add ability to bulk edit members

### ISSUE THREAD

**Issue by pippinsplugins** [pippinsplugins/Restrict-Content-Pro#193]
A lot of users have wanted the option to edit members in bulk.

**Comment by pippinsplugins** [comment]
Oops, wrong commit.

**Comment by pippinsplugins** [comment]
![screen shot 2015-07-24 at 3 45 49 pm](https://cloud.githubusercontent.com/assets/1034109/8884274/18bccd1a-321b-11e5-8e7a-8303a47276a5.png)

**Comment by carter2422** [comment]
Yay!

On Friday, July 24, 2015, Pippin Williamson <notifications@github.com>
wrote:

> [image: screen shot 2015-07-24 at 3 45 49 pm]
> <https://cloud.githubusercontent.com/assets/1034109/8884274/18bccd1a-321b-11e5-8e7a-8303a47276a5.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pippinsplugins/Restrict-Content-Pro/issues/193#issuecomment-124717218>
> .
>


-- 
Jonathan Williamson
http://cgcookie.com

**Comment by tnorthcutt** [comment]
Awesome! :+1:

**Comment by pippinsplugins** [comment]
Merged into `release/2.3` for further testing.
