### ISSUE TITLE
Required custom user fields stop "Upgrade Your Subscription" form

### ISSUE THREAD

**Issue by 2bearstudio** [pippinsplugins/Restrict-Content-Pro#197]
If custom user field presents in user profile, when submit "Upgrade Your Subscription" form, it pops up error message saying (the custom field is required)

I added the custom user fields following this instruction:
https://pippinsplugins.com/adding-custom-user-fields-restrict-content-pro/

**Comment by pippinsplugins** [comment]
Please submit this as a support ticket: https://pippinsplugins.com/plugin-support

Github is for development tracking only.
