### ISSUE TITLE
shortcodes display regardless of being inside [restrict]...[/restrict]

### ISSUE THREAD

**Issue by cliffordp** [pippinsplugins/Restrict-Content-Pro#198]
I have 1 WP user (subscriber) that's not a RCP member. I have zero RCP members.
I do have 1 membership/subscription in RCP settings.
The "blah blah" text won't display, but both of these 2 shortcodes do render:
```
[restrict subscription="1"]
blah blah
[login_form]
[gravityform id="2" title="false" description="true" ajax="true"]
[/restrict]
```

Seems like a bug to me.

Please advise.

**Comment by pippinsplugins** [comment]
See my response to your support ticket.
