### ISSUE TITLE
Update ReCaptcha to APIv2.0

### ISSUE THREAD

**Issue by jb510** [pippinsplugins/Restrict-Content-Pro#199]
Google newser ReCpatcha V2.0 (just click the box) is available and way friendlier for things like registration forms where not losing people to visual captchas is particularly important.

There is a new PHP library available: https://github.com/google/recaptcha

I briefly looked at implementing it here: https://github.com/9seeds/Restrict-Content-Pro/tree/feature/recaptcha-api-v2

Seems like it's working but it's not tested and certainly not quite ready for a PR.

Beyond tidying code I'm assuming the PHP library include is PHP 5.4+ so it needs a version check, maybe on which falls back to APIv2.

Also could be included via composer if that's the way you guys normally load external libraries like this.  I just wanted see if it was an option, it seems to be.

**Comment by pippinsplugins** [comment]
I'm going to get it added for RCP 2.2

**Comment by pippinsplugins** [comment]
Would you be up for sending me a PR so I can look at it closer?

**Comment by jb510** [comment]
Well my fork is currently not working. I need to rewrite more of the return verification than I expected.  I can submit a PR, but do you really want a half finished/broken PR?

**Comment by jb510** [comment]
Also since I seem to do PRs wrong half the time...  you want a PR of /feature/recaptcha-api-v2 against what, master?

**Comment by jb510** [comment]
#200

**Comment by pippinsplugins** [comment]
Could you submit it against the `issue/199` branch?

**Comment by pippinsplugins** [comment]
@jb510 I see that this is not functional yet (as mentioned in your comments). Did you want to finish it up? If not, I can take over.

**Comment by jb510** [comment]
I don't have plans to complete it, at least not any time soon.

**Comment by pippinsplugins** [comment]
Ok I'll take it over.

**Comment by pippinsplugins** [comment]
Merged into release/2.3
