### ISSUE TITLE
Add 2Checkout gateway

### ISSUE THREAD

**Issue by pippinsplugins** [pippinsplugins/restrict-content-pro#203]
2Checkout should be supported

**Comment by jawittdesigns** [comment]
2Checkout recurrence issue need resolved #213

**Comment by pippinsplugins** [comment]
In `issue/203` now.

**Comment by pippinsplugins** [comment]
Moving to 2.3.2

**Comment by pippinsplugins** [comment]
@cklosowski This is almost done. Just two parts left:

1. Finish the INS (webhook listener)
2. Add support for cancelling subscriptions. To do this, you have to have the "lineitem_id" (that's what 2Checkout requires for the cancellation call). To get that, you have to fire an extra API call to retrieve it. I started on it in https://github.com/pippinsplugins/restrict-content-pro/commit/f1af17b46bda7f4cd28ac7ad1b92654745787b03 (charge details)

**Comment by pippinsplugins** [comment]
See https://www.2checkout.com/documentation/api/sales/stop-lineitem-recurring for API docs on cancelling a subscription.

**Comment by pippinsplugins** [comment]
Complete todo items that I"m aware of at this time:

- [ ] Finish INS for updating subscription status based on posts sent by 2checkout
- [ ] Allow 2Checkout subscribers / site admins to cancel subscriptions. See rcp_can_member_cancel()
- [ ] Introduce `rcp_is_2checkout_subscriber()`
- [ ] Add 2Checkout support to rcp_cancel_member_payment_profile() (this needs to be abstracted better but can be done in the future. For now just add new conditional.
- [ ] Complete payment record creation after subscription is created

**Comment by pippinsplugins** [comment]
2Checkout lets admins create new users in their account that are given just API access:
![screen shot 2015-10-24 at 11 04 11 am](https://cloud.githubusercontent.com/assets/1034109/10711385/060f967c-7a3f-11e5-9e95-09ed71caba8b.png)
I think that solves some of our concerns about adding the username/password constants.

**Comment by pippinsplugins** [comment]
Complete!
