### ISSUE TITLE
Unable to get subscription levels

### ISSUE THREAD

**Issue by BorislavZlatanov** [pippinsplugins/Restrict-Content-Pro#211]
When I go to the Subscription Levels menu on a Wordpress multi-site, it always says that there are no levels. Debugging this issue, I see that in /includes/class-rcp-levels.php, on line 135 we have:

$levels = $wpdb->get_results( "SELECT * FROM {$this->db_name} {$where} ORDER BY {$args['orderby']}{$limit};" );

When then continuing to the get_results() method of the db object, it shows the query as "SELECT * FROM restrict_content_pro  ORDER BY list_order". The table prefix is lacking and that is why it is always returning 0 rows.

Now, I am brand new to Wordpress and I don't know when exactly the prefix is supposed to be injected, but from what I see I imagine it would be either at this line of code or somewhere before that. I modified it like this:

$levels = $wpdb->get_results( "SELECT * FROM {$wpdb->prefix}{$this->db_name} {$where} ORDER BY {$args['orderby']}{$limit};" );

and now it is getting the subscription levels.

I haven't checked it, but probably the inserting of subscription levels suffers from the same issue because this too hasn't been working for us. I just manually inserted the data into the table for now.

Hope this helps and let me know if you need any more details from me.

**Comment by pippinsplugins** [comment]
@BorislavZlatanov did you activate it on a multisite network?

**Comment by BorislavZlatanov** [comment]
Yes, it's activated as a plugin on the multisite network.

**Comment by pippinsplugins** [comment]
Activate it in individual sites then it should retrieve them properly.

Does that work as expected for you?

**Comment by BorislavZlatanov** [comment]
Well, the plugin actually does not show in the individual site's plugin area. It just shows in the Network plugins, not in the site's plugins. So I can't activate or deactivate it for the site, just for the Network.

**Comment by pippinsplugins** [comment]
That's because it's network activated. Deactivate it on the network then you can activate it individually.

**Comment by BorislavZlatanov** [comment]
Yes, that was it. Deactivating it on the network and activating it for the site worked.

Thanks for your help and sorry for the confusion.
