### ISSUE TITLE
Add support for WP Approve User plugin

### ISSUE THREAD

**Issue by pippinsplugins** [pippinsplugins/restrict-content-pro#221]
A lot of people have asked for user moderation. This plugin handles it really well: https://wordpress.org/plugins/wp-approve-user/

Let's integrate it.

**Comment by pippinsplugins** [comment]
Some thoughts on this:

1. It should support requiring approval based on the subscription level
2. It should be done in the `integrations` folder / API
3. Members should be able to be approved from the list table and the member edit screen
4. `[subscription_details]` short code should include a message for members pending approval

**Comment by tnorthcutt** [comment]
Additional feature request/idea items:

5. Ability to approve members directly from a notification email to admins (similar to WP core's comment notification emails with "click here to approve, here to mark spam") would be slick, but obv. just "nice to have."
6. Option to send an email to members upon approval would be *very* nice to have – this is needed for the particular project you and I discussed @pippinsplugins 
7. For future extendability, having filters in the right places could enable things like "require approval if email address is at domain x, y, or z" to help with combatting fraud. Same for Geo IP detection.

**Comment by pippinsplugins** [comment]
Definitely agree with all of those.

**Comment by pippinsplugins** [comment]
Complete!
