### ISSUE TITLE
Add Payment Received email

### ISSUE THREAD

**Issue by pippinsplugins** [pippinsplugins/Restrict-Content-Pro#225]
RCP should have an option to send an email when a payment is received. The Stripe add-on used to support this.

**Comment by carter2422** [comment]
:+1:

If it's not already I'd also like to see this have an action so that it can be hooked into for sending these emails through external systems (like Intercom); mostly for the sake of consistency and finer control

**Comment by pippinsplugins** [comment]
:+1:
