### ISSUE TITLE
Add support for Stripe customer Credit

### ISSUE THREAD

**Issue by carter2422** [pippinsplugins/restrict-content-pro#233]
As it is right now RCP does not seem to support adding credit to customers accounts in Stripe. This would be very useful, though. 

Currently if you want to comp someone's account then you must add a negative value invoice item, such that a payment is still created (and thus updates RCP) but doesn't actually charge the user the full subscription amount. 

The current issue is that if you add Credit to a customer's Stripe account, and that credit is greater than the subscription cost, then Stripe will not insert a payment for that customer until the credit is used up. This causes RCP to not update and thus the customer becomes expired in RCP, even though their subscription is still active.

**Comment by pippinsplugins** [comment]
I'm not sure this is something I can fix.

When a customer has credit greater than their payment amount, Stripe doesn't send the webhook that RCP relies on for recording payments.

I may be able to use a different webhook but I'm not sure.

**Comment by carter2422** [comment]
We should be able to tackle this by checking for `starting_balance` during invoicing. I'll try and tackle.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by carter2422** [comment]
Thanks @pippinsplugins!
