### ISSUE TITLE
Stripe users are getting their expiration set one month ahead

### ISSUE THREAD

**Issue by carter2422** [pippinsplugins/Restrict-Content-Pro#235]
I'm not sure when this started but most all Stripe users are getting their expiration in RCP pushed one month ahead of their Stripe renewal date. 

For example, if a user is set to renew on September 20th, then their expiration in RCP will be October 20th. Soon as payment is received on the 20th the expiration will again be pushed ahead an extra month, making it November 20th rather than October 20th.

**Comment by pippinsplugins** [comment]
I saw this happen a month or two ago and fixed it. Are you on latest?

**Comment by carter2422** [comment]
Ah no, we're on 2.2.5. I'll upgrade and confirm. I hadn't seen that fix go in.

**Comment by pippinsplugins** [comment]
https://github.com/pippinsplugins/Restrict-Content-Pro/commit/32b7fc53b613b3a8da49f35d41a348b6aaa86323

**Comment by carter2422** [comment]
K will close out. My bad.
