### ISSUE TITLE
Reduce JS

### ISSUE THREAD

**Issue by termoplus** [pippinsplugins/restrict-content-pro#236]
Hi,
There are many JS files in the plugin.
Is it possible to combine them?

If I add the plugin all JS will be loaded from main page correct? even if user dont use membership plugin all js will be loaded.

thanks

**Comment by pippinsplugins** [comment]
The JS files are not always loaded. On the frontend, only one JS file is loaded.

In the backed, there are several both those are each needed. As each one is a library / plugin, they cannot be combined.
