### ISSUE TITLE
RCP does not account for Paypal's renewal date changes for monthly subscriptions

### ISSUE THREAD

**Issue by etcook** [pippinsplugins/restrict-content-pro#239]
As described here: https://developer.paypal.com/webapps/developer/docs/classic/paypal-payments-standard/integration-guide/subscribe_buttons/

Paypal walks the renewal date for monthly subscriptions that are initiated on the 29th, 30th and 31st. I've confirmed with Paypal that this is the case for both standard and express subscriptions.

> How Subscriptions with Monthly Billing Cycles Work

> For monthly billing cycles, recurring payments are collected on the same day of the month. If the initial recurring payment falls on the 31st, PayPal eventually adjusts the billing cycle to the 1st of the month. If the initial recurring payment falls on the 29th or 30th, PayPal adjusts the billing cycle to the 1st of the month on the following February.

> When Monthly Recurring Payments Are Due and Collected on the 31st

> The subscription terms are:

> $25.99 USD a month; the subscriber signs up on Thursday, July 31.
> The subscriber is billed as follows:

> Thursday, July 31 = $25.99 USD
> Saturday, August 31 = $25.99 USD
> Wednesday, October 1= $25.99 USD
> Saturday, November 1= $25.99 USD
> and so on...
> Notice that no recurring monthly payment was collected in September, but recurring payments were collected roughly every 30 days.

As I see it, we really have two ways to approach this issue.

1. Create support for prorating subscriptions that start on the 29, 30 and 31st, and create the 1st as the proper renewal date.
2. Follow the documented Paypal algorithm and walk the subscription dates accordingly.

Thoughts?

**Comment by pippinsplugins** [comment]
There's no way to pro-rate subscription amounts since the amount is set once and cannot be changed in PayPal. That leaves us with option 2.

I'll see if I can work this out for v2.4

**Comment by carter2422** [comment]
:+1:

**Comment by pippinsplugins** [comment]
I believe I have this fixed. See #284 for changes.

Still testing to be sure.

**Comment by pippinsplugins** [comment]
Unit tests are passing!

**Comment by etcook** [comment]
@pippinsplugins Great job on this. I have some thoughts and would like to know what you think.

1) The subscriptions from the 29th and 30th don't actually get moved to the 1st until the subsequent February. This means the renewals could be off by 2-3 days for nearly an entire year.
2) The subscriptions on the 31st don't get moved to the 1st until a month that has 30 days. This could mean the renewals are off by a day for up to a month or two.
3) You're dynamically adding 2 days to the calculation of the renewals - but that doesn't work for subscriptions started on the 29th, as that would place renewal on the 31st. These would eventually walk to the 1st, and thus suffer the same fate as the current renewals once Paypal walks the subscription to the 1st.

I believe calculating the proper renewal date and hard saving the new renewal date in the db for each calculation might be the best long term approach. Thoughts?

**Comment by pippinsplugins** [comment]
@etcook 

1. Based on my understanding of the PayPal algorithm, the adjustment happens on a month-by-month (or payment by payment period). If the next payment is due to fall on the 29th-31st, it gets walked forward. I've set this up to work the same way. When the expiration date (which is equal to the date of the next payment) is calculated, it walks it forward by 2 days if it lands on the 29th-31st. I don't see how this would result in it being off for an entire year. Am I missing something?

2. No, they get moved on the first renewal before the month that has 29, 30, or 31 days:
```php
$expire_timestamp  = strtotime( '+' . $subscription->duration . ' ' . $subscription->duration_unit . ' 23:59:59', $base_timestamp );
$extension_days    = array( '29', '30', '31' );

if( in_array( date( 'j', $expire_timestamp ), $extension_days ) && 'day' !== $subscription->duration_unit ) {

	/*
	 * Here we extend the expiration date by 2 days in order to account for "walking" payment dates in PayPal.
	 *
	 * See https://github.com/pippinsplugins/restrict-content-pro/issues/239
	 */

	$expiration = date( 'Y-m-d H:i:s', strtotime( $expiration . ' +2 days' ) );
}
```
Did I misunderstand the problem you've raised?

3. You're right, I need to force it to the 1st, not just add 2 days.

The expiration and renewal date are the same thing; it is stored in the DB.

**Comment by pippinsplugins** [comment]
@etcook look better? ^

**Comment by pippinsplugins** [comment]
I believe this is fixed and all unit tests are passing. I'm going to close now but if further issues are noticed, feel free to re-open or open a new issue.

**Comment by etcook** [comment]
@pippinsplugins I believe the examples and explanation provided by PayPal indicate a more complicated "walk" schedule than you anticipate.

There are two schedules:

1) "If the initial recurring payment falls on the 29th or 30th, PayPal adjusts the billing cycle to the 1st of the month on the following February."

Therefore, if a subscription is triggered on March 29th - it doesn't "walk" until the subsequent February (in reality, March 1st). Therefore, the subscription could be off up to a year before it re-aligns.

2) Items on the 31st are handled differently.

"Thursday, July 31 = $25.99 USD
Saturday, August 31 = $25.99 USD
Wednesday, October 1= $25.99 USD
Saturday, November 1= $25.99 USD"

The renewal date doesn't shift until it hits a month with only 30 days, in which it then "walks" to the first of the next month. This isn't explicitly stated, but the example provided would seem to indicate this.

Based on this reading, the subscriptions will be off for at least a month and up to a year even with the fix proposed.

Am I reading this wrong?

**Comment by etcook** [comment]
@pippinsplugins Have you had a chance to look at what I was referencing? Can you reopen this unless I've mistaken?
