### ISSUE TITLE
Question: login URL

### ISSUE THREAD

**Issue by sumobi** [pippinsplugins/restrict-content-pro#250]
@pippinsplugins Any particular reason why the login URL has a query string?
https://github.com/pippinsplugins/restrict-content-pro/blob/master/includes/login-functions.php#L29

As opposed to:
`$url = get_permalink( absint( $rcp_options['login_redirect'] ) );`

The URL would be a lot nicer (/login vs /login/?redirect=http://rcp.dev/register/)

**Comment by pippinsplugins** [comment]
The redirect is necessary for handling the URl that the user is sent to after logging in successfully.

**Comment by sumobi** [comment]
@pippinsplugins :+1:
