### ISSUE TITLE
Undefined index errors when activating/deactivating discount codes when Stripe enabled

### ISSUE THREAD

**Issue by sumobi** [pippinsplugins/restrict-content-pro#254]
- Stripe test gateway activated
- 1 discount code set up

if you try and deactivate or activate a discount code:

    Notice: Undefined index: code in /wp-content/plugins/restrict-content-pro/includes/gateways/stripe/functions.php on line 410

    Notice: Undefined index: unit in /wp-content/plugins/restrict-content-pro/includes/gateways/stripe/functions.php on line 414

    Notice: Undefined index: amount in /wp-content/plugins/restrict-content-pro/includes/gateways/stripe/functions.php on line 424

    Notice: Undefined index: code in /wp-content/plugins/restrict-content-pro/includes/gateways/stripe/functions.php on line 426

Followed by:

    exception 'Stripe\Error\InvalidRequest' with message 'Invalid string id: ' in /wp-content/plugins/restrict-content-pro/includes/libraries/stripe/lib/ApiRequestor.php:144

It seems a simple fix would be to check that a discount code has been posted with `isset( $_POST['code'] )` before running all the other code but I'm not familiar with Stripe enough to test this.

**Comment by pippinsplugins** [comment]
Will get it fixed!
