### ISSUE TITLE
New Subscription emails have old expiration date

### ISSUE THREAD

**Issue by carter2422** [pippinsplugins/restrict-content-pro#256]
When a user becomes `Active` after having been expired/cancelled/otherwise not a member then the `%expiration%` in the welcome email display their old expiration date rather than the new one. 

I believe this is because the status is set before the expiration is updated. See the notes on this user, who reported it:

```
September 17, 2015 19:09:25 - Member's status changed from expired to pending

September 17, 2015 19:09:33 - Member's status changed from pending to active

September 17, 2015 19:09:34 - Member's status changed from active to expired

September 17, 2015 19:09:37 - Member's status changed from expired to active

September 17, 2015 19:09:37 - Member's expiration changed from 2014-03-24 23:59:59 to 2015-10-17 23:59:59
```

**Comment by cklosowski** [comment]
So the `RCP_Member::renew()` method seems to have it in the order of setting expiration, then setting the status update (which is what triggers the emails:
```
$this->set_expiration_date( $expiration );
$this->set_status( $status );
```

@carter2422 what lines were your logging entered at? I'd love to try and replicate with your debugging in place.

**Comment by cklosowski** [comment]
@carter2422 n/m, I see it's in the Member's profile...#noob

**Comment by carter2422** [comment]
Were you able to replicate this @cklosowski?

**Comment by pippinsplugins** [comment]
I've found one place it's in the wrong order, but only when manually updating users.

**Comment by pippinsplugins** [comment]
Correction! I found a few.
