### ISSUE TITLE
issue with user search ajax overlay when no results

### ISSUE THREAD

**Issue by chuckreynolds** [pippinsplugins/restrict-content-pro#263]
**Where:** /wp-admin/admin.php?page=rcp-members

**Problem:**
![screengrab 2015-10-06 at 15 44 07](https://cloud.githubusercontent.com/assets/46185/10325747/0ddc12a8-6c49-11e5-88bf-47286d35681d.png)
When no results found the message wasn't wrapped in an unordered list. 

**Solution:**
Wrap the no results in the same ul/li combo and update the javascript to allow html in the message.

**Fixed:**
![screengrab 2015-10-06 at 16 39 39](https://cloud.githubusercontent.com/assets/46185/10325771/37e73104-6c49-11e5-8514-952cc856138c.png)

**Comment by pippinsplugins** [comment]
Good catch!
