### ISSUE TITLE
adding a new role 500's

### ISSUE THREAD

**Issue by chuckreynolds** [pippinsplugins/restrict-content-pro#265]
When adding a new role from `/wp-admin/admin.php?page=rcp-members` the admin 500's.

![cdpartnerportal_app_wp-admin_admin_php_page_rcp-members](https://cloud.githubusercontent.com/assets/46185/10326475/7f41a28a-6c50-11e5-89cc-68b5d38b28bb.png)

WP -- 4.3.1
RCP -- 2.3.5
no other plugins active

Initially I thought it was just w/ [query-monitor](https://wordpress.org/plugins/query-monitor/) plugin active:
![rcp-error-adduser](https://cloud.githubusercontent.com/assets/46185/10326376/49c82d6e-6c4f-11e5-9b71-e5b51ee012e0.png)

**Comment by pippinsplugins** [comment]
@chuckreynolds What do you mean when adding a new role? RCP doesn't add roles.

Do you mean when adding a subscription to an existing user?

**Comment by chuckreynolds** [comment]
Yeah when adding via this form:
![screengrab 2015-10-06 at 18 18 27](https://cloud.githubusercontent.com/assets/46185/10326978/c9beb6d0-6c56-11e5-8875-3871d7e2bf53.png)

I just now realize that it says "(for existing user)"... I thought, and my use case at the time, was I could use this to add a new member/subscriber. 
If that's truly meant to only `edit` current subscribers... I don't think that submit button should be active unless the username in the username field is actually a user.  I'm assuming that's why it failed. 

in that regard... just needs error handling.

also - how does an admin, in your view, add a new user with an active sub?

**Comment by pippinsplugins** [comment]
I agree: submit button should not be available until a user is selected.

You're right that it failed because it's for existing users only.

This is the form you should use as an admin to create a subscription for a user. You just have to create the user account first.

**Comment by chuckreynolds** [comment]
Right. I get that now. just wasn't immediately apparent to me that's what it was for. 
So flow would be ... 
- admin creates new user via WP User screen.
- admin go to RCP settings and assign a subscription to said user.

Yes?

**Comment by pippinsplugins** [comment]
Yes.

I'll see if I can improve that.

**Comment by pippinsplugins** [comment]
Closing and opening a new issue that describes the suggested enhancement
