### ISSUE TITLE
Refactor rcp_check_for_existing_payment() to use transaction_id

### ISSUE THREAD

**Issue by carter2422** [pippinsplugins/restrict-content-pro#271]
The `rcp_check_for_existing_payment()` function doesn't work reliably and it seems it'd be far more reliable to simply check against transaction IDs. In particular, this would help avoid duplicate payments where the date is different for one reason or another. 

One such example is if an admin has manually entered payments with their transaction IDs after a web hook failure. If that web hook were to be retired it'll currently create duplicate payments as it's comparing the exact date, not the transaction ID.

**Comment by pippinsplugins** [comment]
@carter2422 You can use it like this:
```php
$payments = new RCP_Payments;

if( $payments->payment_exists( $trans_id ) ) {
     // it exists
}
```

**Comment by carter2422** [comment]
Nice. Thanks @pippinsplugins
