### ISSUE TITLE
Active / Welcome email should only send on new accounts and when manually renewing an account

### ISSUE THREAD

**Issue by pippinsplugins** [pippinsplugins/restrict-content-pro#276]
Currently, the `Active` email gets sent anytime a member's status is set to active. This means members receive the same email anytime a payment is processed (which renews their account and sets it to active).

This is incorrect behavior and should not happen.

The email should only be sent when member's go through the registration form.

**Comment by carter2422** [comment]
I've just seen this happen multiple times. It seems this is a recent change?

**Comment by pippinsplugins** [comment]
It was part of 2.3 I believe.

**Comment by carter2422** [comment]
> The email should only be sent when member's go through the registration form.

I don't think this :point_up: is a good solution. Particularly not with Stripe Checkout coming soon. Instead I think we need a way to determine if a user is upgrading for the first time or coming back; each of which should be different emails.

**Comment by pippinsplugins** [comment]
@carter2422 The problem I have run into is trying to best determine _when_ it should be sent. Through the registration form is the only reliable solution I've come up with.

**Comment by carter2422** [comment]
What about using `user_meta` in the same way that you do to determine if an email has been sent to determine if it's a users first time upgrading or if they're returning? 

Going this route you could set the meta during `process_signup()`. 

During initial registration would be more ideal, but that only works for brand new users. Any free user that's been around for a while would not get the flag.

**Comment by pippinsplugins** [comment]
I'll see if I can work that up.

**Comment by pippinsplugins** [comment]
See https://github.com/pippinsplugins/restrict-content-pro/commit/c5a77d62007a2de444647a32e2697c8475c4f577

**Comment by carter2422** [comment]
Excellent! @pippinsplugins to ensure this is set for free users created through other forms, I assume I should update the meta during those registrations?

**Comment by pippinsplugins** [comment]
Yes.
