### ISSUE TITLE
User can upgrade with failed stripe transaction

### ISSUE THREAD

**Issue by tannerm** [pippinsplugins/restrict-content-pro#292]
To recreate the issue, register for an account with RCP then upgrade to a new account and enter an invalid card (if in test mode with Stripe, use 4000000000000069). The transaction will fail, but when you visit the dashboard you will notice that the upgrade happened and the account is active.

Ideally the user should either retain the previous subscription or change to the new subscription with a pending status.

**Comment by pippinsplugins** [comment]
@tannerm This should be resolved with #294

**Comment by tannerm** [comment]
Super, thanks @pippinsplugins!
